services:
  backend:
      image: cubanitoo/atelier-backend:${BACKEND_VERSION:-latest}
      build:
        context: ./backend
      ports:
        - "8787:8787"
      networks:
        - my-network
  
  frontend:
      image: cubanitoo/atelier-frontend:${FRONTEND_VERSION:-latest}
      build:
        context: ./frontend
      ports:
        - "80:80"
      depends_on:
        - backend
      networks:
        - my-network

networks:
  my-network:
    driver: bridge